server:
    port: 9507
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9505/eureka
spring:
  application:
    name: gateway-javaconfig-service
# Hystrix 配置
# hystrix:
#   command:
#     default:
#       execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 5000
#     fallbackCmd: #name of hystrix command
#       execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 5000 # Hystrix 的 fallbackcmd 时间
