server:
    port: 9090
spring:
    rabbitmq:
        host: 113.128.65.64
        port: 7081
        username: nuodi
        password: 123qwe
    cloud:
        stream:
            bindings:
                input:
                    destination: employeeRegistrations
                    group: employeeRegistrationQueue