server:
  port: 8079

spring:
  cloud:
    config:
      uri: http://192.168.1.15:8888
      label: master
  application:
    name: zuul-server
  security:
    user:
      name: "admin"
      password: "password"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 #服务刷新时间配置，每隔这个时间会主动心跳一次
    metadata-map:
      user.name: ${spring.security.user.name}         #These two are needed so that the server
      user.password: ${spring.security.user.password} #can access the protected client endpoints
  client:
    serviceUrl:
      defaultZone: http://192.168.1.15:8090/eureka
zuul:
  routers:
    sale:
      path: /test/**
      service-id: employee-consumer



