spring:
  application:
    name: eureka-server
  boot:
    admin:
      url: https://localhost:8079
      username: admin
      password: password

server:
  port: 8090

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS