server:
  port: 8081

spring:
  application:
    name: employee-producer
  cloud:
    #for spring cloud config
    config:
      label: master
      uri: http://192.168.1.15:8888/
    #srping boot admin config
  boot:
    admin:
      url: https://192.168.1.15:8079
      username: admin
      password: password
      instance:
          service-base-url: http://192.168.1.15:8081/ # 本项目的地址

eureka:
  instance:
    status-page-url: http://${spring.cloud.client.ipaddress}:${server.port}
    # instanceId: ${spring.cloud.client.ipaddress}:${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    instanceId: producer
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

  # the following config for eureka client is fetched from cloud config  
  client:
    serviceUrl:
      defaultZone: http://192.168.1.15:8090/eureka
    #必要的admin配置
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS